scoreboard objectives add farmersdelight_hiddendelight_cooking_pot dummy
scoreboard objectives add farmersdelight_hiddendelight_cutting_board dummy
scoreboard objectives add farmersdelight_hiddendelight_cook dummy